language: python
python:
- '2.7'
services:
- memcached
before_install:
- sudo apt-get update -qq
- sudo apt-get -q install gfortran libatlas-base-dev libatlas-dev liblapack-dev
install:
- pip install ghp-import
- pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
- pip install -r requirements.txt
before_script:
- cd src
- python manage.py syncdb --noinput
script:
- echo "yes" | python manage.py test -v2