language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get -q install gfortran libatlas-base-dev libatlas-dev liblapack-dev
install:
- pip install ghp-import
- pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
- pip install -r requirements.txt
- cd src
script:
- ./manage.py test -v2