language: python
python:
- '2.7'
services:
- memcached
before_install:
- sudo apt-get update -qq
- sudo apt-get -q install gfortran libatlas-base-dev libatlas-dev liblapack-dev
install:
- pip install ghp-import
- pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
- pip install -r requirements.dev.txt
before_script:
- cd src
- ls -l
- python manage.py syncdb --noinput
script:
- echo "yes" | python manage.py test -v2
after_success:
- cd ../doc
- PYTHONPATH=../src make publish
env:
  global:
  - secure: dMa5sKLUi7mjp4YHVj0YTVj4wZ+S+zUWKhPrWA30HpOPzd+s9BoV3fXU30x4Qc+fM/h8CYrtzDe8EZUdwRKNk/2jlIn6fou4UGoO081rRgNwPeKivpOo0uR7iuywyCHJJFQroUaWcJugJn55XtKMYxr0owwAjqI9z5fp4xMytA4=
